/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.demo;

import com.demo.config.AppConfig;
import com.demo.endpoints.CreateChat;
import com.demo.endpoints.CreateMessage;
import com.demo.endpoints.GetChatMessages;
import com.demo.endpoints.GetUserChats;
import com.demo.server.RestServer;

public class App {
    private RestServer server;

    private App(String[] args) {
        final AppConfig config = AppConfig.getInstance();
        server = config.getRestServer();
    }

    public void run() throws Exception {
        // Add our supported endpoints and start the server.
        server.addEndpointHandler(new CreateMessage());
        server.addEndpointHandler(new CreateChat());
        server.addEndpointHandler(new GetUserChats());
        server.addEndpointHandler(new GetChatMessages());
        server.start();
    }

    public static void main(String[] args) {
        try {
            new App(args).run();
        } catch (Exception e) {
            System.out.println("Exception starting app " + e.getMessage());
            System.exit(1);
        }
    }
}
